export const mockSurveys = [
  {
    id: 1,
    name: "General Health and Wellness",
    description:
      "Assess overall health and wellness habits among participants.",
    openingTime: "2025-01-15T08:00:00Z",
    closingTime: "2025-01-20T23:59:59Z",
  },
  {
    id: 2,
    name: "Mental Health Awareness",
    description:
      "Evaluate awareness and attitudes toward mental health resources.",
    openingTime: "2025-02-01T09:00:00Z",
    closingTime: "2025-02-10T18:00:00Z",
  },
  {
    id: 3,
    name: "Fitness and Exercise Habits",
    description: "Gather data on participants' fitness and exercise routines.",
    openingTime: "2025-01-20T10:00:00Z",
    closingTime: "2025-01-31T17:00:00Z",
  },
  {
    id: 4,
    name: "Diet and Nutrition",
    description: "Understand dietary habits and nutritional awareness.",
    openingTime: "2025-01-10T12:00:00Z",
    closingTime: "2025-01-15T23:59:59Z",
  },
  {
    id: 5,
    name: "Stress Management",
    description: "Collect feedback on stress levels and coping mechanisms.",
    openingTime: "2025-02-05T07:00:00Z",
    closingTime: "2025-02-15T22:00:00Z",
  },
  {
    id: 6,
    name: "Sleep Quality",
    description: "Evaluate sleep patterns and the impact on overall health.",
    openingTime: "2025-01-25T09:00:00Z",
    closingTime: "2025-02-05T17:00:00Z",
  },
  {
    id: 7,
    name: "Healthcare Access",
    description:
      "Explore participants' access to and satisfaction with healthcare services.",
    openingTime: "2025-01-18T08:00:00Z",
    closingTime: "2025-01-30T20:00:00Z",
  },
  {
    id: 8,
    name: "Workplace Wellness",
    description:
      "Assess interest and participation in workplace wellness initiatives.",
    openingTime: "2025-01-22T10:00:00Z",
    closingTime: "2025-02-01T23:59:59Z",
  },
  {
    id: 9,
    name: "Preventive Health Screening",
    description:
      "Gather information on awareness and participation in preventive health screenings.",
    openingTime: "2025-02-03T09:30:00Z",
    closingTime: "2025-02-12T18:00:00Z",
  },
  {
    id: 10,
    name: "Chronic Illness Management",
    description:
      "Collect insights on managing chronic conditions and available support.",
    openingTime: "2025-01-12T07:30:00Z",
    closingTime: "2025-01-25T23:59:59Z",
  },
];

export const mockQuestions = [
  { id: 1, text: "How often do you engage in physical activity each week?" },
  {
    id: 2,
    text: "Do you feel comfortable discussing mental health with others?",
  },
  { id: 3, text: "How many days a week do you exercise?" },
  { id: 4, text: "How often do you eat home-cooked meals?" },
  { id: 5, text: "How often do you feel overwhelmed by stress?" },
  { id: 6, text: "How many hours do you sleep on average each night?" },
  { id: 7, text: "Do you have regular access to a primary care physician?" },
  { id: 8, text: "Do you regularly consume fruits and vegetables?" },
  { id: 9, text: "Are you aware of local mental health resources?" },
  { id: 10, text: "What type of exercise do you most enjoy?" },
  { id: 11, text: "Do you track your daily calorie intake?" },
  { id: 12, text: "What techniques do you use to manage stress?" },
  { id: 13, text: "Do you experience difficulty falling asleep?" },
  { id: 14, text: "Are you satisfied with your current healthcare provider?" },
  { id: 15, text: "How would you rate your overall health?" },
  { id: 16, text: "Do you feel stress affects your daily life?" },
  { id: 17, text: "Do you set fitness goals for yourself?" },
  { id: 18, text: "Do you consume any dietary supplements?" },
  { id: 19, text: "Do you find meditation or mindfulness helpful?" },
  { id: 20, text: "Do you feel rested when you wake up in the morning?" },
  {
    id: 21,
    text: "Do you experience any barriers to maintaining a healthy lifestyle?",
  },
  {
    id: 22,
    text: "Have you ever sought help from a mental health professional?",
  },
  { id: 23, text: "Do you work out at a gym or at home?" },
  { id: 24, text: "How frequently do you eat fast food?" },
  { id: 25, text: "How would you describe your work-life balance?" },
  { id: 26, text: "Do you use any sleep aids or supplements?" },
  { id: 27, text: "How much water do you drink daily?" },
  { id: 28, text: "How would you rate your overall mental health?" },
  { id: 29, text: "How long do your workouts typically last?" },
  { id: 30, text: "Do you follow any specific diet plan?" },
  {
    id: 31,
    text: "Have you ever participated in a stress management program?",
  },
  { id: 32, text: "Do you maintain a consistent sleep schedule?" },
  { id: 33, text: "Do you find it challenging to prioritize your health?" },
  { id: 34, text: "Do you take breaks to recharge during your workday?" },
  { id: 35, text: "Do you participate in group fitness activities?" },
  { id: 36, text: "Do you read nutritional labels on food products?" },
  { id: 37, text: "Have you experienced sleep interruptions due to stress?" },
  { id: 38, text: "Have you visited a healthcare provider in the last year?" },
  { id: 39, text: "Do you enjoy trying new healthy recipes?" },
  { id: 40, text: "How often do you take mental health days?" },
  { id: 41, text: "Do you track your fitness progress?" },
  { id: 42, text: "Do you avoid sugary drinks in your diet?" },
  { id: 43, text: "Do you practice gratitude or positive thinking?" },
  { id: 44, text: "Do you have a nighttime routine to improve sleep quality?" },
  { id: 45, text: "Do you have access to affordable healthcare options?" },
  { id: 46, text: "Do you monitor your hydration throughout the day?" },
  { id: 47, text: "How often do you engage in activities that relax you?" },
  {
    id: 48,
    text: "Do you use technology or apps to support your fitness goals?",
  },
  { id: 49, text: "How frequently do you eat whole grains?" },
  {
    id: 50,
    text: "Do you feel your physical health impacts your mental health?",
  },
];

export const mockSurveyQuestionRelations = [
  { id: 1, surveyId: 1, questionId: 1, questionOrder: 1 },
  { id: 2, surveyId: 1, questionId: 8, questionOrder: 2 },
  { id: 3, surveyId: 1, questionId: 15, questionOrder: 3 },
  { id: 4, surveyId: 1, questionId: 21, questionOrder: 4 },
  { id: 5, surveyId: 1, questionId: 27, questionOrder: 5 },

  { id: 6, surveyId: 2, questionId: 2, questionOrder: 1 },
  { id: 7, surveyId: 2, questionId: 9, questionOrder: 2 },
  { id: 8, surveyId: 2, questionId: 16, questionOrder: 3 },
  { id: 9, surveyId: 2, questionId: 22, questionOrder: 4 },
  { id: 10, surveyId: 2, questionId: 28, questionOrder: 5 },

  { id: 11, surveyId: 3, questionId: 3, questionOrder: 1 },
  { id: 12, surveyId: 3, questionId: 10, questionOrder: 2 },
  { id: 13, surveyId: 3, questionId: 17, questionOrder: 3 },
  { id: 14, surveyId: 3, questionId: 23, questionOrder: 4 },
  { id: 15, surveyId: 3, questionId: 29, questionOrder: 5 },

  { id: 16, surveyId: 4, questionId: 4, questionOrder: 1 },
  { id: 17, surveyId: 4, questionId: 11, questionOrder: 2 },
  { id: 18, surveyId: 4, questionId: 18, questionOrder: 3 },
  { id: 19, surveyId: 4, questionId: 24, questionOrder: 4 },
  { id: 20, surveyId: 4, questionId: 30, questionOrder: 5 },

  { id: 21, surveyId: 5, questionId: 5, questionOrder: 1 },
  { id: 22, surveyId: 5, questionId: 12, questionOrder: 2 },
  { id: 23, surveyId: 5, questionId: 19, questionOrder: 3 },
  { id: 24, surveyId: 5, questionId: 25, questionOrder: 4 },
  { id: 25, surveyId: 5, questionId: 31, questionOrder: 5 },

  { id: 26, surveyId: 6, questionId: 6, questionOrder: 1 },
  { id: 27, surveyId: 6, questionId: 13, questionOrder: 2 },
  { id: 28, surveyId: 6, questionId: 20, questionOrder: 3 },
  { id: 29, surveyId: 6, questionId: 26, questionOrder: 4 },
  { id: 30, surveyId: 6, questionId: 32, questionOrder: 5 },

  { id: 31, surveyId: 7, questionId: 7, questionOrder: 1 },
  { id: 32, surveyId: 7, questionId: 14, questionOrder: 2 },
  { id: 33, surveyId: 7, questionId: 21, questionOrder: 3 },
  { id: 34, surveyId: 7, questionId: 27, questionOrder: 4 },
  { id: 35, surveyId: 7, questionId: 34, questionOrder: 5 },

  { id: 36, surveyId: 8, questionId: 9, questionOrder: 1 },
  { id: 37, surveyId: 8, questionId: 18, questionOrder: 2 },
  { id: 38, surveyId: 8, questionId: 22, questionOrder: 3 },
  { id: 39, surveyId: 8, questionId: 31, questionOrder: 4 },
  { id: 40, surveyId: 8, questionId: 33, questionOrder: 5 },

  { id: 41, surveyId: 9, questionId: 10, questionOrder: 1 },
  { id: 42, surveyId: 9, questionId: 25, questionOrder: 2 },
  { id: 43, surveyId: 9, questionId: 29, questionOrder: 3 },
  { id: 44, surveyId: 9, questionId: 30, questionOrder: 4 },
  { id: 45, surveyId: 9, questionId: 38, questionOrder: 5 },

  { id: 46, surveyId: 10, questionId: 11, questionOrder: 1 },
  { id: 47, surveyId: 10, questionId: 23, questionOrder: 2 },
  { id: 48, surveyId: 10, questionId: 28, questionOrder: 3 },
  { id: 49, surveyId: 10, questionId: 35, questionOrder: 4 },
  { id: 50, surveyId: 10, questionId: 42, questionOrder: 5 },
];

export const mockUsers = [
  {
    id: 1,
    firstName: "Emily",
    lastName: "Clark",
    email: "emily.clark@example.com",
  },
  {
    id: 2,
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
  },
  {
    id: 3,
    firstName: "Sophia",
    lastName: "Davis",
    email: "sophia.davis@example.com",
  },
  {
    id: 4,
    firstName: "Daniel",
    lastName: "Martinez",
    email: "daniel.martinez@example.com",
  },
  {
    id: 5,
    firstName: "Olivia",
    lastName: "Brown",
    email: "olivia.brown@example.com",
  },
  {
    id: 6,
    firstName: "James",
    lastName: "Garcia",
    email: "james.garcia@example.com",
  },
  {
    id: 7,
    firstName: "Isabella",
    lastName: "Lopez",
    email: "isabella.lopez@example.com",
  },
  {
    id: 8,
    firstName: "Ethan",
    lastName: "Wilson",
    email: "ethan.wilson@example.com",
  },
  {
    id: 9,
    firstName: "Mia",
    lastName: "Anderson",
    email: "mia.anderson@example.com",
  },
  {
    id: 10,
    firstName: "Alexander",
    lastName: "Taylor",
    email: "alexander.taylor@example.com",
  },
];

export const mockSurveyUserRelations = [
  { id: 1, surveyId: 1, userId: 8 },
  { id: 2, surveyId: 2, userId: 10 },
  { id: 3, surveyId: 3, userId: 5 },
  { id: 4, surveyId: 4, userId: 7 },
  { id: 5, surveyId: 5, userId: 9 },
  { id: 6, surveyId: 6, userId: 4 },
  { id: 7, surveyId: 7, userId: 2 },
  { id: 8, surveyId: 8, userId: 1 },
  { id: 9, surveyId: 9, userId: 6 },
  { id: 10, surveyId: 10, userId: 3 },
];
